#!/bin/bash
# Read from ss (netstat) every X seconds, depending on your disk space.
while true; do
  ss -an | grep -v State | while read line; do
    echo " $line" >> ./net.log &&
    sleep "$1";
  done;
done
