#!/bin/sh
#
#    Start up a daemon for reading the template "net.log" in /var/log for patterns.
########################################################--------------------------------->
sec.pl --input=/var/tmp/learner/net.log --conf=/etc/learner.cfg --log=/var/tmp/learner/learner.log --debug=6
sec.pl --input=/var/tmp/learner/new-catalog.log --conf=/etc/learner-watcher.cfg --log=/var/tmp/learner/learner-watcher.log
