#!/bin/sh
#
#    Start up a daemon for reading the template "net.log" in /var/log for patterns.
########################################################--------------------------------->
sec.pl --input=/var/log/net.log --conf=./learner.cfg --log=./learner/learner.log --debug=6
sec.pl --input=/var/log/new-catalog.log --conf=./learner-watcher.cfg --log=./learner/learner-watcher.log
