#!/bin/bash
# Read from netstat every 2 seconds.
function infinitewatcher () {
while netgar=666 ; do
  netstat -tanWel | while read line;
    do echo "$line" >> /var/log/net.log ;
    sleep 2;
  done
done
}

# Cycle of madness
netgar=666 ;

ps aux | grep net-gargoyle | awk '{print $2}' | grep -v grep | xargs kill -9

while true; do
infinitewatcher
:>/var/log/log/net.log ;
done
ps aux | grep "/bin/bash /usr/local/bin/deny-sorter" | grep -v grep | awk '{print $2}' | xargs kill -9
