#!/bin/bash
# Search for unique IPs with "(\d+)\.(\d+)\.(\d+)\.(\d+)" ss(netstat) output and report new occurrnces.
lockfile -r 0 /var/tmp/lock-catalog-sorter || exit 1
wkdir=/var/tmp/learner
  touch "$wkdir"/lock-catalog-sorter;
  touch "$wkdir"/catalog.log;
  touch "$wkdir"/catalog.tmp;
  touch "$wkdir"/catalog.archive;
  touch "$wkdir"/catalog.last;
  touch "$wkdir"/new.catalog;
  touch "$wkdir"/net.tmp;
  touch "$wkdir"/net.log;
  touch "$wkdir"/lock.dat;
  cp "$wkdir"/catalog.log "$wkdir"/catalog.last;
  cat "$wkdir"/catalog.last >> "$wkdir"/catalog.archive;
  sort -u "$wkdir"/catalog.archive > "$wkdir"/catalog.dat;
  grep -ioP "(\d+)\.(\d+)\.(\d+)\.(\d+)" "$wkdir"/net.log  > "$wkdir"/catalog.log;
  sort -u "$wkdir"/catalog.log > "$wkdir"/catalog.tmp;
  cp "$wkdir"/catalog.tmp "$wkdir"/catalog.log;
  cp "$wkdir"/catalog.last "$wkdir"/catalog.in;
  cat "$wkdir"/catalog.archive |  while read line; do
    lock=$(echo "$line" | tr -cd '[[:alnum:]]._-' );
    touch "$wkdir"/"$lock".lock;
    echo "$line" > "$wkdir"/"$lock".lock;
  done;
  cat "$wkdir"/*lock | sort -u > "$wkdir"/lock.dat;
  sort -u "$wkdir"/net.log > "$wkdir"/net.tmp;
  cp "$wkdir"/net.tmp "$wkdir"/net.log;
  sort -u "$wkdir"/lock.dat > "$wkdir"/lock.dat.tmp;
  cp "$wkdir"/lock.dat.tmp "$wkdir"/lock.dat;
  comm -23 "$wkdir"/net.log "$wkdir"/lock.dat | sort -u > "$wkdir"/new.catalog;
  cat "$wkdir"/new.catalog >> "$wkdir"/new-catalog.log;
  cp "$wkdir"/lock.dat "$wkdir"/net.log;

rm -f "$wkdir"/lock-catalog-sorter;
